version: '3.8'

services:
  openai-console:
    build: .
    container_name: openai-realtime-console
    restart: unless-stopped
    
    env_file:
      - .env

    environment:
     
      - NODE_ENV=production 
      - VIRTUAL_HOST=oepsas-voice.alpi.page
      - LETSENCRYPT_HOST=oepsas-voice.alpi.page

    networks:
      - webproxy

networks:
  webproxy:
    external: true